package io.agcmc.agc.api;

/**
 * AGC runtime features that plugins may inspect or request diagnostics for.
 *
 * <p>Features are categorized by subsystem: Network, Chunks, Entities,
 * World Concurrency, Minigames, Plugin Determinism, and Scale Runtimes.</p>
 */
public enum AGCFeature {
    // --- Core & Latency ---
    HIT_REWIND,
    ADAPTIVE_VIEW_DISTANCE,
    PACKET_PRIORITY_BUDGETING,
    CHUNK_QUEUE_BUDGETING,
    ADAPTIVE_SCALING_PROFILES,
    PLUGIN_THREAD_TRANSLATION,
    PARALLEL_WORLD_TICK,
    EMPTY_WORLD_PACKET_HIBERNATION,
    OPTIMIZATION_ENVELOPE,
    ENTITY_TRACKER_FAST_PATH,

    // --- Minigames Framework ---
    MINIGAME_API,
    MINIGAME_ARENA_SERVICES,

    // --- Scaling Coordinator & Resource Management ---
    SURVIVAL_SCALE_COORDINATOR,
    RESOURCE_EFFICIENCY_ENGINE,
    INTEREST_GRAPH,
    GLOBAL_FAIRNESS_MATRIX,
    SHARED_READ_ONLY_CACHE,
    COMPUTE_TOPOLOGY_PLANNER,
    STORAGE_IO_GOVERNOR,
    SCALE_KERNEL,
    REGION_HOTSPOT_MAP,
    SCALE_CONTROL_PLANE,
    MEMORY_LOCALITY_PLANNER,
    HOTSPOT_EVICTION_PLANNER,
    CACHE_LOCALITY_WINDOW,
    READ_ONLY_WORK_STEALING_PLANNER,
    ADAPTIVE_LOCALITY_RING,
    RESOURCE_PLACEMENT_PLANNER,
    COMPUTE_WASTE_REDUCER,
    SYSTEM_LOAD_SHEPHERD,
    SEMANTIC_HOT_PATH_METER,
    WORKER_ROUTE_PLANNER,
    HOT_PATH_PLAN_CACHE,
    RESOURCE_LOCALITY_SCHEDULER,

    // --- Network & Packet Fanout Subsystem ---
    FANOUT_DEDUPLICATOR,
    NETWORK_FANOUT_KERNEL,
    PACKET_SHAPE_TABLE,
    PLAYER_COHORT_TABLE,
    ENCODING_REUSE_PLANNER,
    NETWORK_DELTA_SHAPE_PLANNER,
    NETWORK_RECIPIENT_COHORT_GRAPH,
    NETWORK_SEND_GRAPH_COMPILER,
    NETWORK_MULTICAST_SHAPE_GRAPH,
    NETWORK_BACKBONE_GRAPH,
    PLAYER_CLUSTER_MOVEMENT_PLANNER,
    NETWORK_BROADCAST_PLANNER,
    NETWORK_COHORT_BACKBONE_CACHE,
    NETWORK_STABLE_DIFF_PLANNER,
    NETWORK_ORDER_VECTOR_COMPILER,

    // --- Chunk Pipeline & Spatial Lookahead ---
    CHUNK_INTENT_PLANNER,
    CHUNK_PIPELINE_KERNEL,
    CHUNK_INTENT_COMPACTOR,
    PLAYER_MOTION_INTENT_MODEL,
    CHUNK_LOOKAHEAD_PLANNER,
    CHUNK_PREDICTIVE_INDEX,
    CHUNK_SPATIAL_ROUTE_PLANNER,
    CHUNK_DEMAND_FORECAST_TABLE,
    CHUNK_WORKSET_SLICER,
    CHUNK_STORM_CONTROLLER,
    CHUNK_TERRAIN_DEMAND_MODEL,
    CHUNK_FRONTIER_SCHEDULER,
    CHUNK_HORIZON_COMPILER,

    // --- Entity Tracking & Observation Grid ---
    ENTITY_VISIBILITY_PRESELECTOR,
    ENTITY_TRACKER_KERNEL,
    ENTITY_BANDING_PLANNER,
    ENTITY_SPATIAL_BAND_INDEX,
    ENTITY_INTERACTION_GRAPH,
    ENTITY_TRACKER_DELTA_INDEX,
    ENTITY_INTEREST_SET_REDUCER,
    ENTITY_WITNESS_INDEX,
    ENTITY_DENSITY_FIELD,
    ENTITY_OBSERVER_MATRIX,
    ENTITY_VISIBILITY_LATTICE,
    ENTITY_OBSERVER_SET_COMPILER,

    // --- World Concurrency & Multiverse ---
    WORLD_LOGIC_PHASE_DAG,
    WORLD_PHASE_EXECUTOR_PLAN,
    UNIFIED_TICK_PLAN_COMPILER,
    WORLD_PHASE_BATCH_COMPILER,
    WORLD_SEMANTIC_SCHEDULER,
    MULTIVERSE_LANE_ALLOCATOR,
    MULTIVERSE_PHASE_MATRIX,
    WORLD_BARRIER_DAG_COMPILER,
    WORLD_READ_ONLY_BATCH_GRAPH,

    // --- Plugin Compatibility & Determinism ---
    THREAD_AFFINITY_TRANSLATOR,
    PLUGIN_LOGIC_TRANSLATOR,
    PLUGIN_BACKPRESSURE_BRIDGE,
    PLUGIN_SEMANTIC_MODEL,
    PLUGIN_CONTRACT_VERIFIER,
    PLUGIN_SEMANTIC_FIREWALL,
    PLUGIN_SEMANTIC_JIT,
    PLUGIN_DETERMINISM_GUARD,
    PLUGIN_COMMIT_SEQUENCER,
    PLUGIN_ORDERED_COMMIT_LEDGER,
    PLUGIN_COMMIT_COALESCER,
    PLUGIN_DETERMINISTIC_TICKET_CACHE,

    // --- Scale Control Planes & Kernels ---
    SCALE16_CONTROL_LAW,
    SCALE17_ALGORITHM_KERNEL,
    SCALE18_CONTROL_PLANE,
    SCALE19_LOGIC_KERNEL,
    SCALE20_LOSSLESS_PIPELINE,
    SCALE21_CRITICAL_PATH_RUNTIME,
    SCALE22_TICK_WORK_COMPILER,
    SCALE23_DISPATCH_TABLE,
    SCALE24_HOT_PATH_RUNTIME
}
