#!/usr/bin/env python3
"""AGC honesty fixes — scripted, exact-string edits to the generated NMS tree.

Why this script exists
----------------------
`paper-server/src/minecraft/**` is git-ignored (Paper convention: it is regenerated by
`paperweight`'s `applyPatches`). The file-editing tools in this workspace respect ignore rules, so
the AGC NMS-tree fixes below cannot be applied with them. They are applied with this script instead,
and every edit is verified afterwards by diffing against the pre-edit tree backup:

    diff -ru paper-server/src/minecraft/java build/verify/minecraft-tree-backup/java

The script is intentionally strict: if an anchor string is missing or ambiguous it fails loudly
instead of writing a partial edit. It preserves CRLF line endings.

What it changes (all of it restores Paper behaviour that AGC had changed without a config gate)
-----------------------------------------------------------------------------------------------
1. Mob.java            - removes the per-tick `(tickCount + id) % 2` AI gate plus the DAP distance
                         throttle and the AI batch split (mobs re-evaluate goals every tick again).
2. Brain.java          - removes the sensor/behaviour throttle (brains sense every tick again).
3. Villager.java       - removes the 1-in-20 brain tick for stationary villagers.
4. ItemEntity.java     - restores vanilla's `(tickCount + id) % 4` condition (drops AGC's 10-tick
                         extension).
5. AbstractArrow.java  - removes the grounded-arrow early return (arrow support-state checks run
                         every tick again).
6. ObserverBlock.java  - removes the depth-64 observer-chain limiter (silently dropped neighbour
                         updates for deeper chains, breaking legitimate redstone machines).
7. ExperienceOrb.java  - gates the orb sleep behind the new `entitySleepOptimizer` flag (default
                         off).
8. PathNavigation.java - gates the async pathfinding pipeline behind the new `asyncPathfinding`
                         flag (default off; off-thread pathfinding also needs a thread-safety proof).
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
NMS_ROOT = REPO_ROOT / "paper-server" / "src" / "minecraft" / "java"

EDITS: list[tuple[str, str, str]] = [
    # ------------------------------------------------------------------ Mob.java
    (
        "net/minecraft/world/entity/Mob.java",
        """        int idBasedTickCount = this.tickCount + this.getId();
        // AGC start - DAP & AI goal batch evaluation
        final boolean evaluateFullAi;
        if (!io.papermc.paper.agc.entity.AgcDapGoalSelector.get().shouldTickMobAi(this, this.tickCount)) {
            evaluateFullAi = false;
        } else if (io.papermc.paper.agc.AgcCapabilityMatrix.isEnabled(io.papermc.paper.agc.AgcCapabilityMatrix.Feature.VILLAGER_AI_OPTIMIZER)) {
            final boolean isEngaged = this.getTarget() != null || this.hurtTime > 0;
            evaluateFullAi = io.papermc.paper.agc.AgcEntityAiBatchProcessor.get().shouldEvaluateAi(this.getId(), this.tickCount, isEngaged);
        } else {
            evaluateFullAi = true;
        }
        if (!evaluateFullAi || (idBasedTickCount % 2 != 0 && this.tickCount > 1)) {
            profiler.push("targetSelector");
            this.targetSelector.tickRunningGoals(false);
            profiler.pop();
            profiler.push("goalSelector");
            this.goalSelector.tickRunningGoals(false);
            profiler.pop();
        } else {
            profiler.push("targetSelector");
            this.targetSelector.tick();
            profiler.pop();
            profiler.push("goalSelector");
            this.goalSelector.tick();
            profiler.pop();
        }
        // AGC end
""",
        """        // AGC - AI cadence honesty fix (2026-09-21): the DAP distance throttle, the per-tick AI
        // batch split and the unconditional (tickCount + id) % 2 gate that used to live here all
        // reduced how often a mob re-evaluated its goals and targets - half rate for EVERY mob,
        // slower still with distance to the nearest player. That is directly perceptible (sluggish
        // skeletons/zombies, mobs that notice you late) and none of it was captured in this repo's
        // patch set, so it was removed: goal and target selectors tick every tick, like Paper.
        profiler.push("targetSelector");
        this.targetSelector.tick();
        profiler.pop();
        profiler.push("goalSelector");
        this.goalSelector.tick();
        profiler.pop();
""",
    ),
    # ------------------------------------------------------------------ Brain.java
    (
        "net/minecraft/world/entity/ai/Brain.java",
        """        // AGC start - Inactive Brain sensor throttling (Pufferfish DAB)
        final boolean shouldTickSensors;
        final boolean shouldTickDap = io.papermc.paper.agc.entity.AgcDapGoalSelector.get().shouldTickBrain(body, level.getGameTime());
        if (!shouldTickDap) {
            shouldTickSensors = false;
        } else if (io.papermc.paper.agc.AgcCapabilityMatrix.isEnabled(io.papermc.paper.agc.AgcCapabilityMatrix.Feature.VILLAGER_AI_OPTIMIZER)) {
            final boolean isEngaged = body instanceof net.minecraft.world.entity.Mob mob && (mob.getTarget() != null || mob.isAggressive());
            shouldTickSensors = io.papermc.paper.agc.AgcEntityAiBatchProcessor.get().shouldTickSensors(body.getId(), level.getGameTime(), isEngaged);
        } else {
            shouldTickSensors = true;
        }
        if (shouldTickSensors) {
            this.tickSensors(level, body);
        }
        // AGC end
        if (shouldTickDap) {
            this.startEachNonRunningBehavior(level, body);
        }
""",
        """        // AGC - brain cadence honesty fix (2026-09-21): the DAP throttle and the AI batch split used
        // to skip this brain's sensor pass and its behaviour pass on most ticks, so mobs noticed
        // players late. Removed: sensors and behaviours run every tick, like Paper.
        this.tickSensors(level, body);
        this.startEachNonRunningBehavior(level, body);
""",
    ),
    # ------------------------------------------------------------------ Villager.java
    (
        "net/minecraft/world/entity/npc/villager/Villager.java",
        """        // AGC start - Villager trading hall brain sleep optimizer
        if (!inactive && !io.papermc.paper.agc.villager.AgcVillagerOptimizer.get().canSkipBrainTick(this, level.getGameTime())) this.getBrain().tick(level, this); // Paper - EAR 2
        // AGC end
""",
        """        // AGC - villager brain cadence honesty fix (2026-09-21): stationary villagers used to skip
        // 19 of every 20 brain ticks, which delayed restocking / POI / gossip behaviour. Removed.
        if (!inactive) { // Paper - EAR 2
            this.getBrain().tick(level, this);
        }
""",
    ),
    # ------------------------------------------------------------------ ItemEntity.java
    (
        "net/minecraft/world/entity/item/ItemEntity.java",
        """            // AGC start - Item static sleep optimizer
            if (this.onGround() && !(this.getDeltaMovement().horizontalDistanceSqr() > 1.0E-5F) && ((this.tickCount + this.getId()) % 4 != 0 || io.papermc.paper.agc.entity.AgcEntitySleepOptimizer.get().canSkipItemPhysics(this, this.tickCount))) { // Paper - Diff on change; ActivationRange immunity
                this.applyEffectsFromBlocksForLastMovements();
            } else {
            // AGC end
""",
        """            // AGC - item sleep honesty fix (2026-09-21): the static-sleep extension used to widen
            // vanilla's (tickCount + id) % 4 motion skip into a 10-tick cadence, so a resting item
            // reacted to a removed support block / new fluid / block effect up to ~half a second
            // late - exactly the timing item-transport builds depend on. Restored to vanilla.
            if (this.onGround() && !(this.getDeltaMovement().horizontalDistanceSqr() > 1.0E-5F) && (this.tickCount + this.getId()) % 4 != 0) { // Paper - Diff on change; ActivationRange immunity
                this.applyEffectsFromBlocksForLastMovements();
            } else {
""",
    ),
    # ------------------------------------------------------------------ AbstractArrow.java
    (
        "net/minecraft/world/entity/projectile/arrow/AbstractArrow.java",
        """            // AGC start - Grounded arrow physics sleep
            if (!this.level().isClientSide() && io.papermc.paper.agc.entity.AgcEntitySleepOptimizer.get().canSkipProjectilePhysics(this, this.tickCount)) {
                this.tickDespawn();
                this.inGroundTime++;
                return;
            }
            // AGC end
""",
        """            // AGC - arrow sleep honesty fix (2026-09-21): the grounded-arrow fast path returned
            // before the vanilla support-state check, so an arrow stuck in a block that was broken
            // or changed kept hovering for up to 19 ticks. Removed: the vanilla in-ground path runs
            // every tick.
""",
    ),
    # ------------------------------------------------------------------ ObserverBlock.java
    (
        "net/minecraft/world/level/block/ObserverBlock.java",
        """        // AGC start - Terminate runaway recursive observer loops
        if (!io.papermc.paper.agc.redstone.AgcRedstoneOptimizer.get().checkObserverChainDepth()) {
            return;
        }
        try {
        // AGC end
        Direction direction = state.getValue(FACING);
        BlockPos oppositePos = pos.relative(direction.getOpposite());
        Orientation orientation = ExperimentalRedstoneUtils.initialOrientation(level, direction.getOpposite(), null);
        level.neighborChanged(oppositePos, this, orientation);
        level.updateNeighborsAtExceptFromFacing(oppositePos, this, direction, orientation);
        // AGC start
        } finally {
            io.papermc.paper.agc.redstone.AgcRedstoneOptimizer.get().decrementObserverChainDepth();
        }
        // AGC end
""",
        """        // AGC - observer depth limiter removed (2026-09-21): the depth-64 ceiling silently dropped
        // neighbour updates for deeper observer chains, which breaks legitimate redstone machines
        // (vanilla has no such ceiling). The vanilla update path is restored.
        Direction direction = state.getValue(FACING);
        BlockPos oppositePos = pos.relative(direction.getOpposite());
        Orientation orientation = ExperimentalRedstoneUtils.initialOrientation(level, direction.getOpposite(), null);
        level.neighborChanged(oppositePos, this, orientation);
        level.updateNeighborsAtExceptFromFacing(oppositePos, this, direction, orientation);
""",
    ),
    # ------------------------------------------------------------------ ExperienceOrb.java
    (
        "net/minecraft/world/entity/ExperienceOrb.java",
        """            // AGC start - ExperienceOrb static sleep optimizer
            if (this.followingPlayer != null || !io.papermc.paper.agc.entity.AgcEntitySleepOptimizer.get().canSkipOrbPhysics(this, this.tickCount)) {
""",
        """            // AGC - orb sleep is opt-in (default off): skipping a resting orb's motion step defers
            // its reaction to block changes by up to nine ticks.
            if (this.followingPlayer != null || !io.papermc.paper.configuration.GlobalConfiguration.get().agc.performance.entitySleepOptimizer || !io.papermc.paper.agc.entity.AgcEntitySleepOptimizer.get().canSkipOrbPhysics(this, this.tickCount)) {
""",
    ),
    # ------------------------------------------------------------------ PathNavigation.java
    (
        "net/minecraft/world/entity/ai/navigation/PathNavigation.java",
        """        // AGC start - Asynchronous Pathfinding Pipeline (Leaf MC)
        if (this.agc$pendingPathFuture != null) {
""",
        """        // AGC - asynchronous pathfinding is opt-in (default off): off-thread pathfinding needs a
        // thread-safety proof for the region snapshot and it delays a mob's first path by a tick.
        if (io.papermc.paper.configuration.GlobalConfiguration.get().agc.performance.asyncPathfinding && this.agc$pendingPathFuture != null) {
""",
    ),
    (
        "net/minecraft/world/entity/ai/navigation/PathNavigation.java",
        """        final long currentTick = net.minecraft.server.MinecraftServer.currentTick;
        if (currentTick > this.agc$lastAsyncSubmitTick + 4L) {
""",
        """        final long currentTick = net.minecraft.server.MinecraftServer.currentTick;
        if (io.papermc.paper.configuration.GlobalConfiguration.get().agc.performance.asyncPathfinding && currentTick > this.agc$lastAsyncSubmitTick + 4L) {
""",
    ),
]


def main() -> int:
    failures: list[str] = []
    applied = 0
    for rel_path, old_lf, new_lf in EDITS:
        path = NMS_ROOT / rel_path
        if not path.is_file():
            failures.append(f"missing file: {rel_path}")
            continue
        text = path.read_text(encoding="utf-8", newline="")
        crlf = "\r\n" in text
        old = old_lf.replace("\n", "\r\n") if crlf else old_lf
        new = new_lf.replace("\n", "\r\n") if crlf else new_lf
        count = text.count(old)
        if count == 0:
            failures.append(f"anchor not found in {rel_path}")
            continue
        if count > 1:
            failures.append(f"anchor ambiguous ({count}x) in {rel_path}")
            continue
        path.write_text(text.replace(old, new), encoding="utf-8", newline="")
        applied += 1
        print(f"  patched {rel_path}")

    print(f"\n{applied}/{len(EDITS)} edits applied")
    if failures:
        print("FAILURES:")
        for f in failures:
            print(f"  - {f}")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
