#!/usr/bin/env python3
"""Generate docs/WIRING.md: feature -> consumer wiring census.

Static analysis: every AgcCapabilityMatrix.Feature enum entry is looked up in
(1) AgcConfigSync.java — is it config-authoritative, and which config key drives it;
(2) production call sites (src/main/java + src/minecraft/java, excluding the matrix,
    config-sync and wiring-audit files themselves) — where isEnabled()/Feature.X is read.

Output is deterministic given the source tree: features with zero production
consumers are listed as DORMANT, features whose AgcConfigSync key is missing are
listed as NOT CONFIG-AUTHORITATIVE. Re-run after touching the matrix or wiring.

Usage: python scripts/agc-wiring-census.py  (from repo root)
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MATRIX = ROOT / "paper-server/src/main/java/io/papermc/paper/agc/AgcCapabilityMatrix.java"
SYNC = ROOT / "paper-server/src/main/java/io/papermc/paper/agc/AgcConfigSync.java"
SCAN_DIRS = [
    ROOT / "paper-server/src/main/java",
    ROOT / "paper-server/src/minecraft/java",
]
EXCLUDE = ("AgcCapabilityMatrix.java", "AgcConfigSync.java", "AgcFeatureWiringAuditTest.java")
EXCLUDE_DIRS = ("agc/AgcCapabilityMatrix.java",)

SAFE_EXCLUDED = {
    # The matrix + its own audit are definition sites, not consumers.
    "io/papermc/paper/agc/AgcCapabilityMatrix.java",
    "io/papermc/paper/agc/AgcConfigSync.java",
}

def parse_features() -> dict[str, str]:
    text = MATRIX.read_text(encoding="utf-8")
    body = text.split("enum Feature {", 1)[1].split("}\n", 1)[0]
    features: dict[str, str] = {}
    for name, desc in re.findall(r"([A-Z_][A-Z0-9_]*)\(\"(.*?)\"", body):
        features[name] = desc
    return features

def parse_sync_bindings() -> dict[str, str]:
    text = SYNC.read_text(encoding="utf-8")
    bindings: dict[str, str] = {}
    for line in text.splitlines():
        m = re.search(r"AgcCapabilityMatrix\.Feature\.([A-Z0-9_]+),\s*(.+);", line)
        if m:
            bindings[m.group(1)] = m.group(2).strip()
    return bindings

def find_consumers(features: dict[str, str]) -> dict[str, list[tuple[str, int, str]]]:
    consumers: dict[str, list[tuple[str, int, str]]] = {f: [] for f in features}
    patterns = {
        f: re.compile(
            r"AgcCapabilityMatrix\.Feature\." + f + r"\b|Feature\." + f + r"\b"
        )
        for f in features
    }
    enable_pat = re.compile(r"AgcCapabilityMatrix\.isEnabled\(")
    for base in SCAN_DIRS:
        for path in base.rglob("*.java"):
            rel = path.relative_to(ROOT).as_posix()
            key = rel.split("paper-server/src/")[1]
            if key in SAFE_EXCLUDED:
                continue
            try:
                text = path.read_text(encoding="utf-8")
            except OSError:
                continue
            if not ("AgcCapabilityMatrix" in text):
                continue
            for f, pat in patterns.items():
                for i, line in enumerate(text.splitlines(), 1):
                    if pat.search(line):
                        consumers[f].append((rel, i, line.strip()))
    return consumers

def main() -> int:
    features = parse_features()
    bindings = parse_sync_bindings()
    consumers = find_consumers(features)

    lines: list[str] = []
    lines.append("<!-- generated by scripts/agc-wiring-census.py; DO NOT EDIT BY HAND -->")
    lines.append("# AGC Feature Wiring Census")
    lines.append("")
    lines.append("Every `AgcCapabilityMatrix.Feature` is listed below with (a) the")
    lines.append("`AgcConfigSync.java` binding that makes it config-authoritative, and (b) the")
    lines.append("production call sites that actually read the gate. A feature with no call")
    lines.append("sites is a dead switch and is marked **DORMANT**; a feature without a")
    lines.append("config binding cannot be turned off by an operator and is marked")
    lines.append("**NOT CONFIG-AUTHORITATIVE**.")
    lines.append("")
    lines.append(f"Total features: {len(features)}")
    lines.append("")

    dormant = []
    not_config = []
    for name in sorted(features):
        desc = features[name]
        binding = bindings.get(name)
        sites = consumers.get(name, [])
        flag = []
        if binding is None:
            flag.append("**NOT CONFIG-AUTHORITATIVE**")
            not_config.append(name)
        if not sites:
            flag.append("**DORMANT (no production consumers)**")
            dormant.append(name)
        lines.append(f"### {name}")
        lines.append("")
        lines.append(f"{desc}")
        lines.append("")
        lines.append(f"- Config binding: `{binding}`" if binding else "- Config binding: **NONE**")
        lines.append(f"- Consumers ({len(sites)}):")
        for rel, lineno, snippet in sites[:8]:
            short = snippet[:120] + ("…" if len(snippet) > 120 else "")
            lines.append(f"  - `{rel}:{lineno}` — `{short}`")
        if len(sites) > 8:
            lines.append(f"  - … and {len(sites) - 8} more")
        lines.append("")

    lines.append("## Summary")
    lines.append("")
    lines.append(f"- DORMANT (no consumers): {len(dormant)} — {', '.join(dormant) if dormant else 'none'}")
    lines.append(f"- NOT config-authoritative: {len(not_config)} — {', '.join(not_config) if not_config else 'none'}")
    lines.append("")

    out = ROOT / "docs/WIRING.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {out.relative_to(ROOT)} ({len(features)} features, "
          f"{len(dormant)} dormant, {len(not_config)} not config-authoritative)")

    # CI guard: refuse to publish a census with unbound features unless they are
    # explicitly acknowledged here.
    acknowledged_unbound = set()
    if not_config and not set(not_config).issubset(acknowledged_unbound):
        print(f"ERROR: features without an AgcConfigSync binding: {', '.join(sorted(not_config))}", file=sys.stderr)
        return 1
    return 0

if __name__ == "__main__":
    sys.exit(main())
